source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               WEB-INF/,\
               resources/,\
               OSGI-INF/org.google.geo.mapping.ui.http.GeoCoderServlet.xml,\
               OSGI-INF/org.google.geo.mapping.ui.http.GeoWebResources.xml,\
               OSGI-INF/
