#ADMIN DIALOG
LOGIN = Login
PROVIDE_IMAGE = Provide an image
NAME_PASSWORD = Name and Password
NAME_PASSWORD_MSG = Please enter your name and password
NAME = Name
PASSWORD = Password
REGISTER = Register
INVALID_NAME_MSG = The provided name is not known
INVALID_PASSWORD_MSG = The provided password is incorrect
EMAIL = Email
EMAIL_MSG = Please provide your email address
INVALID_EMAIL = Invalid Email
INVALID_EMAIL_MSG = The email is not correct

#Roles
ROLE = role
UNKNOWN = Unknown
SUPER_USER = Super User
ADMIN = Admin
CO_WORKER = Coworker
GUEST = Guest