#NA
YES = Yes
NO = No

#Error messages and warnings
ERR_INVALID_ADDRESS_MSG = "Combination of postal code and house number is not valid"

#General tokens
LOCALISATION = en
UNKNOWN = Unknown
UNKNOWN_MSK = Unknown situation
OK = OK
CANCEL = Cancel
IDENTIFIER = Identifier
DELETE = Delete

#Name
NAME = Name
FIRST_NAME = First Name
CALLING_NAME = "Calling name"
PREFIX = Prefix
SURNAME = Surname
NICK_NAME=Nickname
PASSWORD = toegangscode

#Admin
LOCATION = Location
ROLE = Role;
USER_NAME = Username

BIRTH_DATE = Birth Date
TITLE = Title
GENDER = Gender

ETHNICITY = Ethnicity
VOCATION = Vocation
UPASS = U. pass

#Hobbies and Interests
HOBBY = Hobbies and Interests
HOBBIES = Hobbies
INTERESTS = interests

#Vocation
FUNCTION = Function
STUDENT = Student/pupil
RETIRED = Retired

ANDROGYNOUS = Androgynous
A = A
TRANSGENDER = Transsexual
T = T
MALE = Male
M = M
FEMALE = Female
F = V
#UNKNOWN = Onbekend <-- double cross, because it exists already in this file
U = O

ADDRESS = Address
ADDRESS_MSG = Find an Address
STREET = Street
STREET2 = Street Line 2
NUMBER = Number
POSTCODE = Postal Code
TOWN = Town

CONTACT = Contact
CONTACT_TYPE = Contact Type
ADD = Add
REMOVE = Remove

#Contacts
TELEPHONE_HOME = Home Telephone
TELEPHONE_WORK = Work Telephone
MOBILE = Mobile Telephone
FAX = Telefax
EMAIL = Email Address

#Contact Messages
UNKNOWN_MSG = Unknown Media
TELEPHONE_HOME_MSG = Incorrect Telephone Number
TELEPHONE_WORK_MSG = Incorrect Work Telephone Number
MOBILE_MSG = Incorrect Mobile Telephone Number
FAX_MSG = Incorrect Telefax Number
EMAIL_MSG = Incorrect Email Address

RESTRICT = Restrict
CONTACT_TITLE = Enter a New Contact type
CONTACT_TITLE_MSG = Contact types are email, telephone, fax and so on.

#Titles
MISTER = mr
MISSUS = mrs
MISS = ms
DOCTOR = dr

#tooltip
TOOLTIP = tool Tip
TOOLTIP_MSG = The value is not valid for this entry

#Members
MEMBERS = Members
MEMBER_TITLE = Add Member
MEMBER_TITLE_MSG = Add a member to this group

#Search
SEARCH = Search
GO = Go
